New Behind/Ahead indicator segment
AmrEldib/cmder-powerline-prompt pull request #53
Opened 2019-02-13 03:28 UTC by altinokdarici

I have added new segment at the end of the line for git. It shows behind/ahead commits. I have updated screenshot, so you can check the new look.

2020-06-25 14:28 UTC, PKBoo commented
leaving the git directory does not remove the segment. not sure how to fix this myself but if i figure it out i'll submit a pull request

2020-07-09 17:45 UTC, PKBoo requested changes

2020-07-09 17:45 UTC, PKBoo commented on powerline_git.lua
> +    end
> leaving the git directory does not remove the segment. not sure how to fix this myself but if i figure it out i'll submit a pull request

if this change is made, segment is removed when changing the directory

```suggestion
   if segment.isNeeded then 
        addSegment(segment.text, segment.textColor, segment.fillColor)
        if statusSegment.isNeeded then 
          addSegment(statusSegment.text, statusSegment.textColor, statusSegment.fillColor)
        end
    end 
```

2020-07-17 20:23 UTC, altinokdarici commented
@AmrEldib could you please reivew this PR?

2023-03-14 21:46 UTC, closed without merging